### ISSUE TITLE
Support join cluster with auto-approve

### ISSUE THREAD

**Issue by clyang82** [open-cluster-management-io/clusteradm#372]
We have support 
> ManagedClusterAutoApproval will approve a managed cluster registraion request automatically. A registraion request to be automatically approved must be initiated by specific users, these users are specifed with "--cluster-auto-approval-users" flag in the registration hub controller.

https://github.com/open-cluster-management-io/api/blob/ad02e8269c0919e4fc4e546b3e08fb3468130748/feature/feature.go#L61

Even if the cluster enables this feature, when use `clusteradm join ...`, it always asks the user to run `cluseradm accept ...`

The expected behaviour is we can pass "--cluster-auto-approval-user" to `clusteradm join` command so that the CSR is created by this user and can be approved automatically. we do not need to prompt run `clusteradm accept` anymore.

FYI @qiujian16 @skeeey

**Comment by qiujian16** [comment]
I think this has been fixed? @skeeey can we close this one?

**Comment by skeeey** [comment]
yeah, currently, we only need open the feature gate `ManagedClusterAutoApproval` when running `clusteradm init`,  then run the `clusteradm join`, the cluster will bd approved automatically (the `clusteradm accept` is not needed anymore).

**Comment by aii-nozomu-oki** [comment]
@clyang82 pointed out that even when ManagedClusterAutoApproval is enabled, a message prompting the execution of clusteradm accept still appears. This issue has not been fixed in version 0.8.4.

```
Please log onto the hub cluster and run the following command:

    clusteradm accept --clusters [cluster name]
```

**Comment by skeeey** [comment]
@aii-nozomu-oki , yes, we need to eliminate this message if the auto approve is enabled
